### PR TITLE
improve $routeProvider and $route externs

### PR DESCRIPTION
**Pull request by darkdarkdragon**

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
@sledorze my bad. fixed.

**Comment by frabbit** [comment]
Couldn't we get rid of some Dynamics, there are a lot of them?

**Comment by darkdarkdragon** [comment]
@frabbit yeah, I just don't know how. Most of them is fields of typedef which can be function or string.
And I don't know way how to describe that in typedef other then make them dynamic.

**Comment by frabbit** [comment]
@darkdarkdragon you can use haxe.EitherType (https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/EitherType.hx) or better typedef it as angular.support.EitherType because it's not sure if it will stay in the haxe package. It's used a lot in the hxnodejs package, you can find some usage examples here: https://github.com/HaxeFoundation/hxnodejs/search?utf8=%E2%9C%93&q=EitherType

**Comment by darkdarkdragon** [comment]
@frabbit thanks, didn't know about that thing. But I has another problem now - many types are string or function - but any function, with any number of arguments. Is there any way to specify such type?
Without that I need to specify EitherType<String, Dynamic> - which doesn't make any sense :(

**Comment by frabbit** [comment]
Yes, there is the type Function in module haxe.Constraints.

**Comment by darkdarkdragon** [comment]
@frabbit thanks!

**Pull request merged**
